### ISSUE TITLE
Hidden files show up with leading characters, headless sync not working.

### ISSUE THREAD

**Issue by garbofrogman** [vrtmrz/livesync-bridge#10]
First of all, thank you for these tools and all the work you put into them. I'm still working on my setup but am excited to get it working.

I have selfhosted-livesync up and running and want to set up livesync-bridge so that I can use a script to edit .md files directly on my server and have the changes reflected in Obsidian. However, I only got this to work for a minute and have had weird problems since then, even after deleting the database and re-installing both livesync tools.

Currently I am getting messages like this:
bridge-1  | 2/13/2024, 7:37:27 PM       10      WATCH: PROCESS DONE: i.obsidian/workspace.json
bridge-1  | 2/13/2024, 7:37:27 PM       1       WATCH: PROCESSING: i.obsidian/workspace.json

And then the files show up in my CouchDB:
![image](https://github.com/vrtmrz/livesync-bridge/assets/102494168/8f8e6380-b782-4a8b-91df-546f0cb3af5f)

and in Obsidian and File Explorer:
![image](https://github.com/vrtmrz/livesync-bridge/assets/102494168/a64731e9-8d32-4918-a5ec-441b96a23885)
![image](https://github.com/vrtmrz/livesync-bridge/assets/102494168/4c058722-c702-44db-aa1d-0957ca39ba70)

Whenever I open the vault, I get a bunch of messages which only happens after starting livesync-bridge:
![image](https://github.com/vrtmrz/livesync-bridge/assets/102494168/d9ae3856-f043-4d01-b476-ce4767c42485)

I edited the docker-compose to include the directory where I save my vaults (not sure where they're expected to be located by default):
```
version: "2.1"
services:
  bridge:
    build: .
    volumes:
      - ./data:/app/data
      - ./dat:/app/dat
      - "G:/obsidian/vaults:/obsidian/vaults"
    restart: unless-stopped
```

Here's my config.json:
```
{
    "peers": [
        {
            "type": "couchdb",
            "name": "testname",
            "group": "test",
            "database": "livesynctest",
            "username": "myusername",
            "password": "My-CoUcH-Db-PaSsW0Rd",
            "url": "https://my.couchdb.url",
            "customChunkSize": 100,
            "minimumChunkSize": 20,
            "passphrase": "",
            "obfuscatePassphrase": "",
            "baseDir": ""
        },
        {
            "type": "storage",
            "group": "test",
            "name": "storage-test",
            "baseDir": "/obsidian/vaults/livesynctest/",
            "scanOfflineChanges": true
        }   
    ]
}
```

**Comment by vrtmrz** [comment]
Sorry for being late!
It seems that hidden files have not been handled successfully.
I will check it later!

**Comment by vrtmrz** [comment]
I have fixed a hidden file issue today!
Now these files (Which prefixed i:...) will be ignored.
Would you please check the behaviour?

**Comment by garbofrogman** [comment]
Nice work! Those files no longer appear.
