### ISSUE TITLE
Recommendation: Support database/folder synchronization in different warehouses

### ISSUE THREAD

**Issue by jiongxuan** [vrtmrz/livesync-bridge#2]
Hi, please ask vrtmrz:

I want to synchronize multiple Databases (Vaults) to multiple folders one by one for backup of original files without opening Obsidian. For example:

1. DB_A --> Storage_A
2. DB_B --> Storage_B
...

Judging from the code and documentation, LiveSync-Bridge currently supports the synchronization of a single warehouse (referring to the contents of the same folder). The main purpose is for sharing, but there is no "one-to-one" synchronization (used for backup and folders export) instance.

Please help to see if it is currently supported? And how to support? grateful!

Finally, a big thank you to contributors such as vrtmrz for making great Obsidian plug-ins, solving synchronization issues, and continuing to update them. Keep up the good work!

**Comment by vrtmrz** [comment]
I am so honoured to contribute to enriching and making our environment self-controllable with you! 

Indeed we had to instantiate multiple LiveSync-Bridge. However, thanks to your insights, I have realised that it might be a good keyhole for the new features. 

Now, we have a new property `group` in each peer configuration, and each change of peers will be dispatched only to the same group. 
At the moment, it simply uses complete matching, but we can add some functions here as our need. I felt very extensibility for this. It seems to have advantages over simply having many instances.

I have pushed the repo with these implementations. Would you mind if I ask you to check the behaviour, please?

**Comment by jiongxuan** [comment]
What a great method! By using Group, we not only achieve one-to-one (through group) requirements, but also provide good scalability for the future.

I expect to try this repo in the next two days. If I encounter any problems, I will communicate with you as soon as possible. Finally, thank you again for your quick response and active support!
